<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <title>AxZ Compare</title>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>
<body>
    <div id="questionAnswer" class="container">
       <header class="major">
           <h1>Vamos Começar?<br /></h1>
           <h4>Numa escala de 0 a 5 (onde 5 é muito importante), quão importante você considera cada característica do Smartphone?</h4>
       </header>
       <div v-for="(item_values,item_name) in criteria" >
        <label><b>{{item_values.Name}}</b> é {{numtoword(Math.round(item_values.user_choice))}} para meu {{main_item}}?</label>
        <br>
        <input id="item_values.tag" type="range" min="0" max="5" step="0.1" v-model="item_values.user_choice">{{item_values.user_choice}} 
        </input>
        <br>
    </div>

<section>
    <br/>
    <h3>Os melhores dispositivos pra você são:</h3>
    <ul class="actions special">
        <li v-for="top_item in top_itens">
          <!--({{item.total}})-->
          <b>{{ top_item.Nome }}</b> {{top_item.total}}
          <span  v-if="criteria[1].user_choice>2.5">,com câmera de {{top_item.Camera}}</span>
          <span  v-if="criteria[3].user_choice>2.5">,com {{top_item.Processamento}} de Processamento</span>
          <span  v-if="criteria[0].user_choice>2.5">,com {{top_item.Tela}}</span>
          <a :href="'https://www.buscape.com.br/search/'+top_item.Nome"> R${{top_item["MELHOR PREÇO"]}},00 (preço aproximado)</a>
        </li>
    </ul>
</section>

</div>


</body>
</html>

<script type="text/javascript">
    var smartphones = 
    [
    {
        "Nome": "Redmi 7A",
        "Custo Beneficio": 10,
        "Hardware": 7.2,
        "MELHOR PREÇO": 520,
        "Mpx": 13,
        "Tamanho Tela": 5.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 5.4 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Max Pro (M1)",
        "Custo Beneficio": 10,
        "Hardware": 8,
        "MELHOR PREÇO": 719,
        "Mpx": 13,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": 5000
    },
    {
        "Nome": "Asus ZenFone Max Plus (M2)",
        "Custo Beneficio": 9.8,
        "Hardware": 7.9,
        "MELHOR PREÇO": 719,
        "Mpx": 12,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.3 1080x2280",
        "Battery": ""
    },
    {
        "Nome": "Lenovo Vibe K6",
        "Custo Beneficio": 9.8,
        "Hardware": 7.2,
        "MELHOR PREÇO": 569,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto E5",
        "Custo Beneficio": 9.7,
        "Hardware": 6.5,
        "MELHOR PREÇO": 509,
        "Mpx": 13,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5.7 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 2",
        "Custo Beneficio": 9.2,
        "Hardware": 7.2,
        "MELHOR PREÇO": 858,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 2.3 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G5",
        "Custo Beneficio": 9.2,
        "Hardware": 7.4,
        "MELHOR PREÇO": 639,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Redmi Note 7",
        "Custo Beneficio": 9.2,
        "Hardware": 8.5,
        "MELHOR PREÇO": 938,
        "Mpx": 48,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 48 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.3 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Max Shot",
        "Custo Beneficio": 9.2,
        "Hardware": 8.1,
        "MELHOR PREÇO": 799,
        "Mpx": 12,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.3 1080x2280",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi A2 Lite",
        "Custo Beneficio": 9.1,
        "Hardware": 8,
        "MELHOR PREÇO": 799,
        "Mpx": 12,
        "Tamanho Tela": 5.8,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.8 1080x2280",
        "Battery": ""
    },
    {
        "Nome": "LG Q6",
        "Custo Beneficio": 9.1,
        "Hardware": 7.4,
        "MELHOR PREÇO": 632,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.1.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "LG G3",
        "Custo Beneficio": 9.1,
        "Hardware": 7.2,
        "MELHOR PREÇO": 599,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 2.5 GHz",
        "Tela": "Display 5.5 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G7 Play",
        "Custo Beneficio": 9.1,
        "Hardware": 7.3,
        "MELHOR PREÇO": 621,
        "Mpx": 13,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.7 720x1512",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G6",
        "Custo Beneficio": 8.9,
        "Hardware": 7.9,
        "MELHOR PREÇO": 773,
        "Mpx": 12,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.7 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Redmi 6A",
        "Custo Beneficio": 8.9,
        "Hardware": 6.2,
        "MELHOR PREÇO": 471,
        "Mpx": 13,
        "Tamanho Tela": 5.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 2 GHz",
        "Tela": "Display 5.4 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G6 Plus",
        "Custo Beneficio": 8.9,
        "Hardware": 8.1,
        "MELHOR PREÇO": 785,
        "Mpx": 12,
        "Tamanho Tela": 5.9,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.9 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi A2",
        "Custo Beneficio": 8.9,
        "Hardware": 8.2,
        "MELHOR PREÇO": 879,
        "Mpx": 12,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Zoom S",
        "Custo Beneficio": 8.9,
        "Hardware": 7.8,
        "MELHOR PREÇO": 999,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Redmi Note 6 Pro",
        "Custo Beneficio": 8.9,
        "Hardware": 8.1,
        "MELHOR PREÇO": 881,
        "Mpx": 12,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 6.3 1080x2280",
        "Battery": ""
    },
    {
        "Nome": "LG G7 ThinQ",
        "Custo Beneficio": 8.8,
        "Hardware": 9.1,
        "MELHOR PREÇO": 1549,
        "Mpx": 16,
        "Tamanho Tela": 6.1,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6.1 1440x3120",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A10",
        "Custo Beneficio": 8.8,
        "Hardware": 6.9,
        "MELHOR PREÇO": 559,
        "Mpx": 13,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 6.2 720x1520",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J4 Plus",
        "Custo Beneficio": 8.7,
        "Hardware": 6.7,
        "MELHOR PREÇO": 567,
        "Mpx": 13,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 6 720x1480",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy M20",
        "Custo Beneficio": 8.6,
        "Hardware": 7.8,
        "MELHOR PREÇO": 809,
        "Mpx": 13,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 6.3 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi 8 Lite",
        "Custo Beneficio": 8.6,
        "Hardware": 8.2,
        "MELHOR PREÇO": 1004,
        "Mpx": 12,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.3 1080x2280",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi Play",
        "Custo Beneficio": 8.5,
        "Hardware": 7.5,
        "MELHOR PREÇO": 763,
        "Mpx": 12,
        "Tamanho Tela": 5.8,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.1 GHz",
        "Tela": "Display 5.8 1080x2280",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Max (M2)",
        "Custo Beneficio": 8.5,
        "Hardware": 7.2,
        "MELHOR PREÇO": 683,
        "Mpx": 13,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.3 720x1520",
        "Battery": ""
    },
    {
        "Nome": "Meizu M6 Note",
        "Custo Beneficio": 8.5,
        "Hardware": 7.7,
        "MELHOR PREÇO": 799,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.1.2",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G4",
        "Custo Beneficio": 8.5,
        "Hardware": 7.3,
        "MELHOR PREÇO": 1045,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G7",
        "Custo Beneficio": 8.4,
        "Hardware": 8.1,
        "MELHOR PREÇO": 879,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.2 1080x2270",
        "Battery": ""
    },
    {
        "Nome": "LG K12 Plus",
        "Custo Beneficio": 8.4,
        "Hardware": 6.8,
        "MELHOR PREÇO": 619,
        "Mpx": 16,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.7 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G5S",
        "Custo Beneficio": 8.4,
        "Hardware": 7.5,
        "MELHOR PREÇO": 775,
        "Mpx": 16,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A30",
        "Custo Beneficio": 8.3,
        "Hardware": 8,
        "MELHOR PREÇO": 879,
        "Mpx": 16,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 6.4 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 4",
        "Custo Beneficio": 8.3,
        "Hardware": 7.9,
        "MELHOR PREÇO": 949,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Lenovo K8 Plus",
        "Custo Beneficio": 8.3,
        "Hardware": 7.5,
        "MELHOR PREÇO": 795,
        "Mpx": 13,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2.1 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "LG K9 TV",
        "Custo Beneficio": 8.3,
        "Hardware": 5.7,
        "MELHOR PREÇO": 395,
        "Mpx": 8,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 7.1.2",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.3 GHz",
        "Tela": "Display 5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G7 Plus",
        "Custo Beneficio": 8.2,
        "Hardware": 8.3,
        "MELHOR PREÇO": 1039,
        "Mpx": 16,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 6.2 1080x2270",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi 9 SE",
        "Custo Beneficio": 8.2,
        "Hardware": 9,
        "MELHOR PREÇO": 1683,
        "Mpx": 48,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 48 Mpx",
        "Processamento": "8 Core 2.4 GHz",
        "Tela": "Display 6 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G5S Plus",
        "Custo Beneficio": 8.2,
        "Hardware": 7.8,
        "MELHOR PREÇO": 911,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Multilaser MS80X",
        "Custo Beneficio": 8.2,
        "Hardware": 7.7,
        "MELHOR PREÇO": 848,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.2 1080x2246",
        "Battery": ""
    },
    {
        "Nome": "Asus Zenfone 3 Max (tela 5.5) 2GB RAM",
        "Custo Beneficio": 8.2,
        "Hardware": 7.3,
        "MELHOR PREÇO": 779,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy M30",
        "Custo Beneficio": 8.2,
        "Hardware": 8,
        "MELHOR PREÇO": 999,
        "Mpx": 13,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 6.4 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Redmi 5 Plus",
        "Custo Beneficio": 8.2,
        "Hardware": 7.8,
        "MELHOR PREÇO": 698,
        "Mpx": 12,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G5 Plus",
        "Custo Beneficio": 8.2,
        "Hardware": 7.8,
        "MELHOR PREÇO": 679,
        "Mpx": 12,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J",
        "Custo Beneficio": 8.1,
        "Hardware": 6.8,
        "MELHOR PREÇO": 648,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 4.3",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 2.3 GHz",
        "Tela": "Display 5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Alcatel Idol 4",
        "Custo Beneficio": 8.1,
        "Hardware": 7,
        "MELHOR PREÇO": 699,
        "Mpx": 13,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Lenovo Vibe K5",
        "Custo Beneficio": 8.1,
        "Hardware": 7.1,
        "MELHOR PREÇO": 719,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 5.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 3",
        "Custo Beneficio": 8.1,
        "Hardware": 7.7,
        "MELHOR PREÇO": 934,
        "Mpx": 16,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Redmi 7",
        "Custo Beneficio": 8,
        "Hardware": 7.2,
        "MELHOR PREÇO": 749,
        "Mpx": 12,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.3 720x1520",
        "Battery": ""
    },
    {
        "Nome": "TCL C9",
        "Custo Beneficio": 8,
        "Hardware": 6.5,
        "MELHOR PREÇO": 599,
        "Mpx": 12,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 12 Mpx",
        "Processamento": "4 Core 1.5 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G6 Play",
        "Custo Beneficio": 8,
        "Hardware": 7,
        "MELHOR PREÇO": 639,
        "Mpx": 13,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.7 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A7 2018",
        "Custo Beneficio": 8,
        "Hardware": 8.3,
        "MELHOR PREÇO": 1243,
        "Mpx": 24,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 24 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6 1080x2220",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J6",
        "Custo Beneficio": 8,
        "Hardware": 7,
        "MELHOR PREÇO": 699,
        "Mpx": 13,
        "Tamanho Tela": 5.6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 5.6 720x1480",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Selfie (ZD551KL)",
        "Custo Beneficio": 8,
        "Hardware": 7.1,
        "MELHOR PREÇO": 975,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy M10",
        "Custo Beneficio": 8,
        "Hardware": 6.9,
        "MELHOR PREÇO": 699,
        "Mpx": 13,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 6.2 720x1520",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A20",
        "Custo Beneficio": 7.9,
        "Hardware": 7,
        "MELHOR PREÇO": 710,
        "Mpx": 13,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 6.4 720x1560",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J5 Prime",
        "Custo Beneficio": 7.9,
        "Hardware": 6.3,
        "MELHOR PREÇO": 699,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J4",
        "Custo Beneficio": 7.9,
        "Hardware": 6.5,
        "MELHOR PREÇO": 628,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A50",
        "Custo Beneficio": 7.9,
        "Hardware": 8.4,
        "MELHOR PREÇO": 1279,
        "Mpx": 25,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 25 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.4 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 5",
        "Custo Beneficio": 7.8,
        "Hardware": 8.1,
        "MELHOR PREÇO": 1079,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 6.2 1080x2246",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A6 Plus",
        "Custo Beneficio": 7.8,
        "Hardware": 8.1,
        "MELHOR PREÇO": 1319,
        "Mpx": 16,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6 1080x2220",
        "Battery": ""
    },
    {
        "Nome": "Redmi Go",
        "Custo Beneficio": 7.8,
        "Hardware": 5.4,
        "MELHOR PREÇO": 399,
        "Mpx": 8,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A5 2016",
        "Custo Beneficio": 7.8,
        "Hardware": 7.2,
        "MELHOR PREÇO": 799,
        "Mpx": 13,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi MI 9",
        "Custo Beneficio": 7.8,
        "Hardware": 9.2,
        "MELHOR PREÇO": 2131,
        "Mpx": 48,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 48 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6.4 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Redmi 6",
        "Custo Beneficio": 7.7,
        "Hardware": 6.8,
        "MELHOR PREÇO": 699,
        "Mpx": 12,
        "Tamanho Tela": 5.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.4 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J6 Plus",
        "Custo Beneficio": 7.7,
        "Hardware": 6.8,
        "MELHOR PREÇO": 721,
        "Mpx": 13,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 6 720x1480",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto X4",
        "Custo Beneficio": 7.6,
        "Hardware": 8.1,
        "MELHOR PREÇO": 1299,
        "Mpx": 12,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "LG G4",
        "Custo Beneficio": 7.6,
        "Hardware": 7.6,
        "MELHOR PREÇO": 1349,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "6 Core 1.8 GHz",
        "Tela": "Display 5.5 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Alcatel Pixi 4 (tela 4)",
        "Custo Beneficio": 7.6,
        "Hardware": 4,
        "MELHOR PREÇO": 194,
        "Mpx": 8,
        "Tamanho Tela": 4,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.3 GHz",
        "Tela": "Display 4 480x800",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Selfie (Novo)",
        "Custo Beneficio": 7.6,
        "Hardware": 6.4,
        "MELHOR PREÇO": 709,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Pocophone F1",
        "Custo Beneficio": 7.6,
        "Hardware": 8.7,
        "MELHOR PREÇO": 1583,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6.2 1080x2246",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G7 Power",
        "Custo Beneficio": 7.6,
        "Hardware": 7.3,
        "MELHOR PREÇO": 799,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.2 720x1520",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto Z",
        "Custo Beneficio": 7.6,
        "Hardware": 7.7,
        "MELHOR PREÇO": 999,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.8 GHz",
        "Tela": "Display 5.5 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S8",
        "Custo Beneficio": 7.6,
        "Hardware": 8.8,
        "MELHOR PREÇO": 1799,
        "Mpx": 12,
        "Tamanho Tela": 5.8,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.8 1440x2960",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto E5 Plus",
        "Custo Beneficio": 7.6,
        "Hardware": 6.5,
        "MELHOR PREÇO": 683,
        "Mpx": 12,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 12 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 6 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Blu R2 Plus",
        "Custo Beneficio": 7.5,
        "Hardware": 6.8,
        "MELHOR PREÇO": 742,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 5 Selfie Pro",
        "Custo Beneficio": 7.5,
        "Hardware": 7.9,
        "MELHOR PREÇO": 1149,
        "Mpx": 16,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 7.1.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Meizu m5 Note",
        "Custo Beneficio": 7.5,
        "Hardware": 6.6,
        "MELHOR PREÇO": 699,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Huawei P10 Lite",
        "Custo Beneficio": 7.5,
        "Hardware": 7.4,
        "MELHOR PREÇO": 939,
        "Mpx": 12,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.9 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "LG G4 Beat",
        "Custo Beneficio": 7.5,
        "Hardware": 7,
        "MELHOR PREÇO": 799,
        "Mpx": 13,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 5.1.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A9",
        "Custo Beneficio": 7.4,
        "Hardware": 8.5,
        "MELHOR PREÇO": 1529,
        "Mpx": 24,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 24 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.3 1080x2220",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 3 (tela 5.5)",
        "Custo Beneficio": 7.4,
        "Hardware": 7.7,
        "MELHOR PREÇO": 1055,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto Z3 Play",
        "Custo Beneficio": 7.3,
        "Hardware": 8,
        "MELHOR PREÇO": 1249,
        "Mpx": 12,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J7 Prime 2",
        "Custo Beneficio": 7.3,
        "Hardware": 7.8,
        "MELHOR PREÇO": 1099,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto E6 Plus",
        "Custo Beneficio": 7.3,
        "Hardware": 6.9,
        "MELHOR PREÇO": 809,
        "Mpx": 13,
        "Tamanho Tela": 6.1,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.1 720x1560",
        "Battery": ""
    },
    {
        "Nome": "LG Q6 Plus",
        "Custo Beneficio": 7.3,
        "Hardware": 7.3,
        "MELHOR PREÇO": 949,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.1.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.5 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto Z2 Play",
        "Custo Beneficio": 7.3,
        "Hardware": 7.8,
        "MELHOR PREÇO": 1104,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.1.1",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S9",
        "Custo Beneficio": 7.3,
        "Hardware": 8.8,
        "MELHOR PREÇO": 1996,
        "Mpx": 12,
        "Tamanho Tela": 5.8,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 5.8 1440x2960",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 5Z",
        "Custo Beneficio": 7.2,
        "Hardware": 8.7,
        "MELHOR PREÇO": 1849,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6.2 1080x2240",
        "Battery": ""
    },
    {
        "Nome": "LG K11 Alpha",
        "Custo Beneficio": 7.2,
        "Hardware": 5.6,
        "MELHOR PREÇO": 469,
        "Mpx": 8,
        "Tamanho Tela": 5.3,
        "Sistema Operacional": "Android 7.1.2",
        "Camera": "Foto 8 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.3 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Quantum YOU E",
        "Custo Beneficio": 7.2,
        "Hardware": 5.5,
        "MELHOR PREÇO": 465,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.3 GHz",
        "Tela": "Display 5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi 8",
        "Custo Beneficio": 7.2,
        "Hardware": 8.7,
        "MELHOR PREÇO": 1915,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6.2 1080x2248",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia M5",
        "Custo Beneficio": 7.1,
        "Hardware": 7.3,
        "MELHOR PREÇO": 949,
        "Mpx": 21.5,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 5.0",
        "Camera": "Foto 21.5 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A8 2018",
        "Custo Beneficio": 7.1,
        "Hardware": 8,
        "MELHOR PREÇO": 1259,
        "Mpx": 16,
        "Tamanho Tela": 5.6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.6 1080x2220",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A8 Plus 2018",
        "Custo Beneficio": 7.1,
        "Hardware": 7.9,
        "MELHOR PREÇO": 1259,
        "Mpx": 16,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6 1080x2220",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S6",
        "Custo Beneficio": 7.1,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1088,
        "Mpx": 16,
        "Tamanho Tela": 5.1,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.1 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J7 Prime",
        "Custo Beneficio": 7.1,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1079,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi 9T Pro",
        "Custo Beneficio": 7.1,
        "Hardware": 9.2,
        "MELHOR PREÇO": 2297,
        "Mpx": 48,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 48 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6.4 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Multilaser MS60Z",
        "Custo Beneficio": 7,
        "Hardware": 5.7,
        "MELHOR PREÇO": 499,
        "Mpx": 13,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.3 GHz",
        "Tela": "Display 6 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 4 Selfie Pro",
        "Custo Beneficio": 7,
        "Hardware": 7.9,
        "MELHOR PREÇO": 1231,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "LG K12 Max",
        "Custo Beneficio": 7,
        "Hardware": 6.9,
        "MELHOR PREÇO": 854,
        "Mpx": 13,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.3 720x1520",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Zoom",
        "Custo Beneficio": 7,
        "Hardware": 7.3,
        "MELHOR PREÇO": 998,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 2.5 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G4 Plus",
        "Custo Beneficio": 7,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1045,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto X Style",
        "Custo Beneficio": 7,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1099,
        "Mpx": 21,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 5.1.1",
        "Camera": "Foto 21 Mpx",
        "Processamento": "6 Core 1.6 GHz",
        "Tela": "Display 5.7 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Huawei P30 Lite",
        "Custo Beneficio": 7,
        "Hardware": 8.3,
        "MELHOR PREÇO": 1495,
        "Mpx": 24,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 24 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.2 1080x2312",
        "Battery": ""
    },
    {
        "Nome": "Huawei P20 Lite",
        "Custo Beneficio": 7,
        "Hardware": 8.1,
        "MELHOR PREÇO": 1589,
        "Mpx": 16,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.4 1080x2310",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia XZ1",
        "Custo Beneficio": 7,
        "Hardware": 8.6,
        "MELHOR PREÇO": 1873,
        "Mpx": 19,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 19 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J2 Pro 2018",
        "Custo Beneficio": 6.9,
        "Hardware": 5.9,
        "MELHOR PREÇO": 549,
        "Mpx": 8,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 7.1",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5 540x960",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A7 2017",
        "Custo Beneficio": 6.9,
        "Hardware": 7.8,
        "MELHOR PREÇO": 720,
        "Mpx": 16,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.9 GHz",
        "Tela": "Display 5.7 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Huawei P Smart 2019",
        "Custo Beneficio": 6.9,
        "Hardware": 7.9,
        "MELHOR PREÇO": 1299,
        "Mpx": 13,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.2 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A70",
        "Custo Beneficio": 6.9,
        "Hardware": 8.5,
        "MELHOR PREÇO": 1599,
        "Mpx": 32,
        "Tamanho Tela": 6.7,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 32 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.7 1080x2400",
        "Battery": ""
    },
    {
        "Nome": "Nokia 5",
        "Custo Beneficio": 6.9,
        "Hardware": 6.6,
        "MELHOR PREÇO": 845,
        "Mpx": 13,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.2 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Multilaser MS80",
        "Custo Beneficio": 6.9,
        "Hardware": 6.8,
        "MELHOR PREÇO": 999,
        "Mpx": 16,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.7 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Huawei G8",
        "Custo Beneficio": 6.9,
        "Hardware": 7.1,
        "MELHOR PREÇO": 986,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto Z Play",
        "Custo Beneficio": 6.9,
        "Hardware": 7.9,
        "MELHOR PREÇO": 1299,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto X Play",
        "Custo Beneficio": 6.9,
        "Hardware": 7.3,
        "MELHOR PREÇO": 1045,
        "Mpx": 21,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.1.1",
        "Camera": "Foto 21 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 5 Selfie",
        "Custo Beneficio": 6.9,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1158,
        "Mpx": 16,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 7.1.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "LG K12 Prime",
        "Custo Beneficio": 6.8,
        "Hardware": 7.1,
        "MELHOR PREÇO": 989,
        "Mpx": 16,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.3 720x1520",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J2 Core",
        "Custo Beneficio": 6.8,
        "Hardware": 5,
        "MELHOR PREÇO": 439,
        "Mpx": 8,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5.5 540x960",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Redmi Note 4",
        "Custo Beneficio": 6.8,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1152,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Max Plus (M1)",
        "Custo Beneficio": 6.8,
        "Hardware": 6.9,
        "MELHOR PREÇO": 949,
        "Mpx": 16,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.7 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "LG Q7 Plus",
        "Custo Beneficio": 6.8,
        "Hardware": 7,
        "MELHOR PREÇO": 994,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.5 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 4 Selfie",
        "Custo Beneficio": 6.8,
        "Hardware": 6.8,
        "MELHOR PREÇO": 899,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S8 Plus",
        "Custo Beneficio": 6.8,
        "Hardware": 8.8,
        "MELHOR PREÇO": 2609,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.2 1440x2960",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto Z2 Force",
        "Custo Beneficio": 6.8,
        "Hardware": 8.6,
        "MELHOR PREÇO": 2499,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.1 GHz",
        "Tela": "Display 5.5 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi 8 Pro",
        "Custo Beneficio": 6.8,
        "Hardware": 8.8,
        "MELHOR PREÇO": 2199,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6.2 1080x2248",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Live (L1)",
        "Custo Beneficio": 6.8,
        "Hardware": 5.6,
        "MELHOR PREÇO": 521,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5.5 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone Go ZB500KL",
        "Custo Beneficio": 6.8,
        "Hardware": 5.8,
        "MELHOR PREÇO": 550,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1 GHz",
        "Tela": "Display 5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J4 Core",
        "Custo Beneficio": 6.7,
        "Hardware": 5.4,
        "MELHOR PREÇO": 499,
        "Mpx": 8,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 6 720x1480",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J8",
        "Custo Beneficio": 6.7,
        "Hardware": 7.3,
        "MELHOR PREÇO": 1088,
        "Mpx": 16,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6 720x1480",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy Note 5",
        "Custo Beneficio": 6.7,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1200,
        "Mpx": 16,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.7 2560x1440",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi Max 3",
        "Custo Beneficio": 6.7,
        "Hardware": 7.9,
        "MELHOR PREÇO": 1770,
        "Mpx": 12,
        "Tamanho Tela": 6.9,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 1.7 GHz",
        "Tela": "Display 6.9 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi Mix 2",
        "Custo Beneficio": 6.7,
        "Hardware": 8.3,
        "MELHOR PREÇO": 1696,
        "Mpx": 12,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S9 Plus",
        "Custo Beneficio": 6.7,
        "Hardware": 8.9,
        "MELHOR PREÇO": 2239,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6.2 1440x2960",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S7",
        "Custo Beneficio": 6.7,
        "Hardware": 8,
        "MELHOR PREÇO": 1795,
        "Mpx": 12,
        "Tamanho Tela": 5.1,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 5.1 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J7 Pro",
        "Custo Beneficio": 6.7,
        "Hardware": 7.7,
        "MELHOR PREÇO": 1199,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone SE",
        "Custo Beneficio": 6.7,
        "Hardware": 7.4,
        "MELHOR PREÇO": 1159,
        "Mpx": 12,
        "Tamanho Tela": 4,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "2 Core 1.8 GHz",
        "Tela": "Display 4 640x1136",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 5S",
        "Custo Beneficio": 6.1,
        "Hardware": 7,
        "MELHOR PREÇO": 1249,
        "Mpx": 8,
        "Tamanho Tela": 4,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 8 Mpx",
        "Processamento": "2 Core 1.3 GHz",
        "Tela": "Display 4 640x1136",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 6S Plus",
        "Custo Beneficio": 6.1,
        "Hardware": 7.9,
        "MELHOR PREÇO": 1772,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "2 Core 2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 6S",
        "Custo Beneficio": 6,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1543,
        "Mpx": 12,
        "Tamanho Tela": 4.7,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "2 Core 1.8 GHz",
        "Tela": "Display 4.7 750x1334",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 6",
        "Custo Beneficio": 5.9,
        "Hardware": 7.1,
        "MELHOR PREÇO": 1614,
        "Mpx": 8,
        "Tamanho Tela": 4.7,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 8 Mpx",
        "Processamento": "2 Core 1.4 GHz",
        "Tela": "Display 4.7 750x1334",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 7 Plus",
        "Custo Beneficio": 5.9,
        "Hardware": 8.4,
        "MELHOR PREÇO": 2719,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "4 Core 2.2 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 8 Plus",
        "Custo Beneficio": 5.9,
        "Hardware": 8.7,
        "MELHOR PREÇO": 3519,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "6 Core 2.1 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 7",
        "Custo Beneficio": 5.8,
        "Hardware": 8,
        "MELHOR PREÇO": 2419,
        "Mpx": 12,
        "Tamanho Tela": 4.7,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "4 Core 2 GHz",
        "Tela": "Display 4.7 750x1334",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 8",
        "Custo Beneficio": 5.7,
        "Hardware": 8.4,
        "MELHOR PREÇO": 2991,
        "Mpx": 12,
        "Tamanho Tela": 4.7,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "6 Core 2.1 GHz",
        "Tela": "Display 4.7 750x1334",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone XR",
        "Custo Beneficio": 5.6,
        "Hardware": 8.7,
        "MELHOR PREÇO": 3783,
        "Mpx": 12,
        "Tamanho Tela": 6.1,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "6 Core 2.1 GHz",
        "Tela": "Display 6.1 828x1792",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone XS Max",
        "Custo Beneficio": 5.3,
        "Hardware": 8.9,
        "MELHOR PREÇO": 5587,
        "Mpx": 12,
        "Tamanho Tela": 6.5,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "6 Core 2.1 GHz",
        "Tela": "Display 6.5 1242x2688",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone X",
        "Custo Beneficio": 5.3,
        "Hardware": 8.8,
        "MELHOR PREÇO": 4693,
        "Mpx": 12,
        "Tamanho Tela": 5.8,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "6 Core 2.1 GHz",
        "Tela": "Display 5.8 1125x2436",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone XS",
        "Custo Beneficio": 5.2,
        "Hardware": 8.9,
        "MELHOR PREÇO": 5500,
        "Mpx": 12,
        "Tamanho Tela": 5.8,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 12 Mpx",
        "Processamento": "6 Core 2.1 GHz",
        "Tela": "Display 5.8 1125x2436",
        "Battery": ""
    },
    {
        "Nome": "Apple iPhone 6 Plus",
        "Custo Beneficio": 5.2,
        "Hardware": 7.5,
        "MELHOR PREÇO": 2399,
        "Mpx": 8,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "iOS 12",
        "Camera": "Foto 8 Mpx",
        "Processamento": "2 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Nokia 6",
        "Custo Beneficio": 6.7,
        "Hardware": 7.7,
        "MELHOR PREÇO": 1295,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A5 2017",
        "Custo Beneficio": 6.7,
        "Hardware": 7.6,
        "MELHOR PREÇO": 996,
        "Mpx": 16,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.9 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia Z5",
        "Custo Beneficio": 6.7,
        "Hardware": 7.7,
        "MELHOR PREÇO": 1048,
        "Mpx": 23,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 5.1.1",
        "Camera": "Foto 23 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia XZ2 Compact",
        "Custo Beneficio": 6.7,
        "Hardware": 8.7,
        "MELHOR PREÇO": 3324,
        "Mpx": 19,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 19 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 5 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Huawei Mate 20 Lite",
        "Custo Beneficio": 6.6,
        "Hardware": 8.1,
        "MELHOR PREÇO": 1589,
        "Mpx": 20,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 20 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.3 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S10e",
        "Custo Beneficio": 6.6,
        "Hardware": 8.9,
        "MELHOR PREÇO": 2399,
        "Mpx": 12,
        "Tamanho Tela": 5.8,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 5.8 1080x2280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S10",
        "Custo Beneficio": 6.6,
        "Hardware": 9.2,
        "MELHOR PREÇO": 2799,
        "Mpx": 12,
        "Tamanho Tela": 6.1,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6.1 1440x3040",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy Note 9",
        "Custo Beneficio": 6.6,
        "Hardware": 8.9,
        "MELHOR PREÇO": 2652,
        "Mpx": 12,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6.4 1440x2960",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy Note 8",
        "Custo Beneficio": 6.5,
        "Hardware": 8.9,
        "MELHOR PREÇO": 2551,
        "Mpx": 12,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.3 1440x2960",
        "Battery": ""
    },
    {
        "Nome": "Blu Vivo 8",
        "Custo Beneficio": 6.5,
        "Hardware": 6.9,
        "MELHOR PREÇO": 1049,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.5 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Mi Mix 3",
        "Custo Beneficio": 6.5,
        "Hardware": 8.8,
        "MELHOR PREÇO": 2429,
        "Mpx": 12,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6.4 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto M",
        "Custo Beneficio": 6.5,
        "Hardware": 6.9,
        "MELHOR PREÇO": 1059,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Huawei Mate 10 Lite",
        "Custo Beneficio": 6.4,
        "Hardware": 7.7,
        "MELHOR PREÇO": 1420,
        "Mpx": 16,
        "Tamanho Tela": 5.9,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5.9 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S10 Plus",
        "Custo Beneficio": 6.3,
        "Hardware": 9.3,
        "MELHOR PREÇO": 3199,
        "Mpx": 12,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6.4 1440x3040",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A7",
        "Custo Beneficio": 6.3,
        "Hardware": 7,
        "MELHOR PREÇO": 1169,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 4.4.4",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Blu Vivo 6",
        "Custo Beneficio": 6.3,
        "Hardware": 6.6,
        "MELHOR PREÇO": 1029,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Blu Vivo XL4",
        "Custo Beneficio": 6.3,
        "Hardware": 6.8,
        "MELHOR PREÇO": 1093,
        "Mpx": 13,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.2 720x1520",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Black Shark",
        "Custo Beneficio": 6.3,
        "Hardware": 8.6,
        "MELHOR PREÇO": 2879,
        "Mpx": 12,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Huawei Y9",
        "Custo Beneficio": 6.3,
        "Hardware": 7.8,
        "MELHOR PREÇO": 1599,
        "Mpx": 13,
        "Tamanho Tela": 6.5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.5 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Huawei Mate 20",
        "Custo Beneficio": 6.2,
        "Hardware": 8.7,
        "MELHOR PREÇO": 2689,
        "Mpx": 12,
        "Tamanho Tela": 6.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.5 1080x2244",
        "Battery": ""
    },
    {
        "Nome": "Huawei P30",
        "Custo Beneficio": 6.2,
        "Hardware": 9.2,
        "MELHOR PREÇO": 3489,
        "Mpx": 40,
        "Tamanho Tela": 6.1,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 40 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.1 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Huawei Y7",
        "Custo Beneficio": 6.2,
        "Hardware": 7.1,
        "MELHOR PREÇO": 1259,
        "Mpx": 13,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.3 720x1520",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S7 Edge",
        "Custo Beneficio": 6.2,
        "Hardware": 8,
        "MELHOR PREÇO": 1799,
        "Mpx": 12,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.0",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 5.5 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A80",
        "Custo Beneficio": 6.1,
        "Hardware": 8.4,
        "MELHOR PREÇO": 2299,
        "Mpx": 48,
        "Tamanho Tela": 6.7,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 48 Mpx",
        "Processamento": "8 Core 1.9 GHz",
        "Tela": "Display 6.7 1080x2400",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S6 edge",
        "Custo Beneficio": 6,
        "Hardware": 7.5,
        "MELHOR PREÇO": 1583,
        "Mpx": 16,
        "Tamanho Tela": 5.1,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.1 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia XZ",
        "Custo Beneficio": 6,
        "Hardware": 7.8,
        "MELHOR PREÇO": 1795,
        "Mpx": 23,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 23 Mpx",
        "Processamento": "4 Core 2.2 GHz",
        "Tela": "Display 5.2 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "LG G8s ThinQ",
        "Custo Beneficio": 6,
        "Hardware": 9,
        "MELHOR PREÇO": 3499,
        "Mpx": 12,
        "Tamanho Tela": 6.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6.2 1080x2248",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J7 Metal (2016)",
        "Custo Beneficio": 6,
        "Hardware": 6.7,
        "MELHOR PREÇO": 1167,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Blu Pure XR",
        "Custo Beneficio": 5.9,
        "Hardware": 6.7,
        "MELHOR PREÇO": 1197,
        "Mpx": 16,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.5 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Huawei Mate 20 Pro",
        "Custo Beneficio": 5.9,
        "Hardware": 9.4,
        "MELHOR PREÇO": 4899,
        "Mpx": 40,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 40 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.4 1440x3120",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 4 Max",
        "Custo Beneficio": 5.9,
        "Hardware": 6.3,
        "MELHOR PREÇO": 1079,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 4 Max ZC520KL",
        "Custo Beneficio": 5.9,
        "Hardware": 6.8,
        "MELHOR PREÇO": 1245,
        "Mpx": 13,
        "Tamanho Tela": 5.2,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 5.2 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 3 Deluxe",
        "Custo Beneficio": 5.8,
        "Hardware": 7.9,
        "MELHOR PREÇO": 1990,
        "Mpx": 23,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 23 Mpx",
        "Processamento": "4 Core 2.2 GHz",
        "Tela": "Display 5.7 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 4 Max 32GB",
        "Custo Beneficio": 5.8,
        "Hardware": 6.7,
        "MELHOR PREÇO": 1298,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 8.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Huawei P30 Pro",
        "Custo Beneficio": 5.8,
        "Hardware": 9.2,
        "MELHOR PREÇO": 4504,
        "Mpx": 40,
        "Tamanho Tela": 6.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 40 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6.5 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "LG G5 SE",
        "Custo Beneficio": 5.8,
        "Hardware": 7.8,
        "MELHOR PREÇO": 2555,
        "Mpx": 16,
        "Tamanho Tela": 5.3,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.5 GHz",
        "Tela": "Display 5.3 1440x2560",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A8s",
        "Custo Beneficio": 5.7,
        "Hardware": 8.7,
        "MELHOR PREÇO": 3357,
        "Mpx": 24,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 24 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 6.4 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A7 2016",
        "Custo Beneficio": 5.7,
        "Hardware": 7.1,
        "MELHOR PREÇO": 1549,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.1.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia XA Ultra",
        "Custo Beneficio": 5.7,
        "Hardware": 7.3,
        "MELHOR PREÇO": 1699,
        "Mpx": 21.5,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 21.5 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 6 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 3 Ultra",
        "Custo Beneficio": 5.6,
        "Hardware": 7.6,
        "MELHOR PREÇO": 2499,
        "Mpx": 23,
        "Tamanho Tela": 6.8,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 23 Mpx",
        "Processamento": "8 Core 1.6 GHz",
        "Tela": "Display 6.8 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Huawei Mate 20 X",
        "Custo Beneficio": 5.6,
        "Hardware": 8.9,
        "MELHOR PREÇO": 4149,
        "Mpx": 40,
        "Tamanho Tela": 7.2,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 40 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 7.2 1080x2244",
        "Battery": ""
    },
    {
        "Nome": "Xiaomi Black Shark 2",
        "Custo Beneficio": 5.6,
        "Hardware": 9.1,
        "MELHOR PREÇO": 4299,
        "Mpx": 48,
        "Tamanho Tela": 6.4,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 48 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 6.4 1080x2340",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia XA1",
        "Custo Beneficio": 5.5,
        "Hardware": 6.6,
        "MELHOR PREÇO": 1417,
        "Mpx": 23,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 23 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy J7",
        "Custo Beneficio": 5.5,
        "Hardware": 6.3,
        "MELHOR PREÇO": 1278,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.5 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy Note 10 Plus",
        "Custo Beneficio": 5.5,
        "Hardware": 9.2,
        "MELHOR PREÇO": 5399,
        "Mpx": 12,
        "Tamanho Tela": 6.8,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6.8 1440x3040",
        "Battery": ""
    },
    {
        "Nome": "Blu Vivo X",
        "Custo Beneficio": 5.5,
        "Hardware": 6.6,
        "MELHOR PREÇO": 1437,
        "Mpx": 13,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2.1 GHz",
        "Tela": "Display 6 720x1440",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy Note 10",
        "Custo Beneficio": 5.4,
        "Hardware": 8.9,
        "MELHOR PREÇO": 4769,
        "Mpx": 12,
        "Tamanho Tela": 6.3,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.3 GHz",
        "Tela": "Display 6.3 1080x2280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S5",
        "Custo Beneficio": 5.4,
        "Hardware": 7.2,
        "MELHOR PREÇO": 1843,
        "Mpx": 16,
        "Tamanho Tela": 5.1,
        "Sistema Operacional": "Android 6.0.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "4 Core 2.5 GHz",
        "Tela": "Display 5.1 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia XA",
        "Custo Beneficio": 5.4,
        "Hardware": 6.1,
        "MELHOR PREÇO": 1099,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 2 GHz",
        "Tela": "Display 5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Cat S31",
        "Custo Beneficio": 5.4,
        "Hardware": 6,
        "MELHOR PREÇO": 1344,
        "Mpx": 8,
        "Tamanho Tela": 4.6,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.1 GHz",
        "Tela": "Display 4.6 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia XZ2",
        "Custo Beneficio": 5.4,
        "Hardware": 8.7,
        "MELHOR PREÇO": 4090,
        "Mpx": 19,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 19 Mpx",
        "Processamento": "8 Core 2.2 GHz",
        "Tela": "Display 5.7 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Google Pixel 3",
        "Custo Beneficio": 5.3,
        "Hardware": 8.5,
        "MELHOR PREÇO": 3765,
        "Mpx": 12.2,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12.2 Mpx",
        "Processamento": "8 Core 2.1 GHz",
        "Tela": "Display 5.5 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Huawei Mate 10 Pro",
        "Custo Beneficio": 5.1,
        "Hardware": 8.4,
        "MELHOR PREÇO": 3807,
        "Mpx": 12,
        "Tamanho Tela": 6,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.1 GHz",
        "Tela": "Display 6 1080x2160",
        "Battery": ""
    },
    {
        "Nome": "Quantum V",
        "Custo Beneficio": 5.1,
        "Hardware": 6.6,
        "MELHOR PREÇO": 1447,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.3 GHz",
        "Tela": "Display 5.5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S6 edge plus",
        "Custo Beneficio": 5,
        "Hardware": 7.4,
        "MELHOR PREÇO": 2095,
        "Mpx": 16,
        "Tamanho Tela": 5.7,
        "Sistema Operacional": "Android 5.1.1",
        "Camera": "Foto 16 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.7 2560x1440",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy S4 Active",
        "Custo Beneficio": 5,
        "Hardware": 6.3,
        "MELHOR PREÇO": 1741,
        "Mpx": 8,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 5.0.2",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.9 GHz",
        "Tela": "Display 5 1080x1920",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia Z5 Premium",
        "Custo Beneficio": 5,
        "Hardware": 8,
        "MELHOR PREÇO": 3989,
        "Mpx": 23,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.1.1",
        "Camera": "Foto 23 Mpx",
        "Processamento": "8 Core 1.8 GHz",
        "Tela": "Display 5.5 2160x3840",
        "Battery": ""
    },
    {
        "Nome": "Huawei P20",
        "Custo Beneficio": 4.9,
        "Hardware": 8.4,
        "MELHOR PREÇO": 2479,
        "Mpx": 12,
        "Tamanho Tela": 5.8,
        "Sistema Operacional": "Android 9",
        "Camera": "Foto 12 Mpx",
        "Processamento": "8 Core 2.1 GHz",
        "Tela": "Display 5.8 1080x2244",
        "Battery": ""
    },
    {
        "Nome": "Cat S60",
        "Custo Beneficio": 4.8,
        "Hardware": 6.9,
        "MELHOR PREÇO": 2449,
        "Mpx": 13,
        "Tamanho Tela": 4.7,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.4 GHz",
        "Tela": "Display 4.7 720x1280",
        "Battery": ""
    },
    {
        "Nome": "LG Optimus G",
        "Custo Beneficio": 4.7,
        "Hardware": 5.9,
        "MELHOR PREÇO": 1106,
        "Mpx": 13,
        "Tamanho Tela": 4.7,
        "Sistema Operacional": "Android 4.1.2",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.5 GHz",
        "Tela": "Display 4.7 768x1280",
        "Battery": ""
    },
    {
        "Nome": "Sony Xperia L1",
        "Custo Beneficio": 4.5,
        "Hardware": 5.5,
        "MELHOR PREÇO": 854,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 7.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Asus ZenFone 2 Laser",
        "Custo Beneficio": 4.4,
        "Hardware": 5.9,
        "MELHOR PREÇO": 1259,
        "Mpx": 13,
        "Tamanho Tela": 5.5,
        "Sistema Operacional": "Android 5.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.2 GHz",
        "Tela": "Display 5.5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Motorola Moto G (3a Ger) 16GB",
        "Custo Beneficio": 4.4,
        "Hardware": 6,
        "MELHOR PREÇO": 1329,
        "Mpx": 13,
        "Tamanho Tela": 5,
        "Sistema Operacional": "Android 5.1.1",
        "Camera": "Foto 13 Mpx",
        "Processamento": "4 Core 1.4 GHz",
        "Tela": "Display 5 720x1280",
        "Battery": ""
    },
    {
        "Nome": "Samsung Galaxy A3",
        "Custo Beneficio": 4.3,
        "Hardware": 5.2,
        "MELHOR PREÇO": 1097,
        "Mpx": 8,
        "Tamanho Tela": 4.5,
        "Sistema Operacional": "Android 4.4.4",
        "Camera": "Foto 8 Mpx",
        "Processamento": "4 Core 1.2 GHz",
        "Tela": "Display 4.5 540x960",
        "Battery": ""
    },
    {
        "Nome": "LG K10",
        "Custo Beneficio": 4.3,
        "Hardware": 5.4,
        "MELHOR PREÇO": 699,
        "Mpx": 13,
        "Tamanho Tela": 5.3,
        "Sistema Operacional": "Android 6.0",
        "Camera": "Foto 13 Mpx",
        "Processamento": "8 Core 1.1 GHz",
        "Tela": "Display 5.3 720x1280",
        "Battery": ""
    }
    ];
</script>

<script type="text/javascript">
function fib(n) {
    return n**1.6180339887
};
var example1 = new Vue({
  el: '#questionAnswer',
  data: {
  	main_item:"Smartphone",
  	criteria:[
      //{"key":"battery","Name": 	"Bateria"			,"tag":"tag_bat"	,"user_choice":1 ,"multiplier":0, "true_value":0, "table_column_name":""},
      {"key":"screen", "Name": 	"Tela Grande"		,"tag":"tag_screen"	,"user_choice":1 ,"multiplier":2, "true_value":0, "table_column_name":"Tamanho Tela"},
      {"key":"camera" ,"Name":"Qualidade de Câmera"	,"tag":"tag_cam"	,"user_choice":1 ,"multiplier":0.133, "true_value":0, "table_column_name":"Mpx"},
      {"key":"price"	,"Name":"Baixo Custo"		,"tag":"tag_price"	,"user_choice":1 ,"multiplier":-0.01, "true_value":0, "table_column_name":"MELHOR PREÇO"},
      {"key":"hardware", "Name":"Potência e Velocidade","tag":"tag_hardw","user_choice":1,"multiplier":1, "true_value":0, "table_column_name":"Hardware"},
      ],
      items: smartphones,
      my_pref_price:2,my_pref_cam: 2,my_pref_speed:2,my_pref_size:2,my_pref_bat:2,my_pref_res:2
  },
  methods : {
    numtoword: function (x) {
      var worddict = 
      {
          0:"irrelevante",
          1:"indiferente",
          2:"interessante",
          3:"importante",
          4:"muito importante",
          5:"imprescindível"
      }
      return worddict[x]
      }
    },
computed: {

    top_itens: function () {
      for (x in this.items) {
        this.items[x]["total"] = 0
        for (crit in this.criteria){
            this.items[x]["total"] += crit.true_value*this.items[x].table_column_name
        };
        //-0.01   * fib(this.my_pref_price)  * this.items[x]["MELHOR PREÇO"]+
        //+0.133  * fib(this.my_pref_cam)    * this.items[x]["Mpx"]+
        //+1      * fib(this.my_pref_speed)  * this.items[x]["Hardware"]+
        //+2      * fib(this.my_pref_size)   * this.items[x]["Tamanho Tela"]
        //;
        //this.items[x]["match"]=
        //this.items[x]["total"]/(
        //  -fib(this.my_pref_price)
        //  +fib(this.my_pref_cam)
        //  +fib(this.my_pref_speed)
        //  +fib(this.my_pref_size)
        //  );
        //this.items[x]["match"]=parseFloat(10*this.items[x]["match"]).toFixed(2)+"%";
        this.items[x]["total"]=parseFloat(this.items[x]["total"]).toFixed(2);
    }
    this.items.sort(function (a, b) {return a["total"]<b["total"];});
    return this.items.slice(0,3)
},


}
})

</script>
